### ISSUE TITLE
Hoshi set text programmatically after it's drawn

### ISSUE THREAD

**Issue by cartmanguo** [raulriera/TextFieldEffects#13]
Hello,Raul
I’ m using HoshiTextField,everything works fine if I enter text from keyboard.But when I set the text of textfield manually,like textfield.text = “abcdefg”,the placeholder text does not move up, so the text being set got covered by the placeholder text.Is there any way the fix the problem?
Thanks.

**Comment by raulriera** [comment]
Hmmm didn't try those scenarios. I guess a property observer on the text property would solve this issue. I will take a look when I have some free time :)

**Comment by raulriera** [comment]
Can you share some code? I tried this on the demo application and it's working correctly

**Comment by cartmanguo** [comment]
it happens when I use a pickerview as the inputview of the textfield.
when the textfield begins edting,I want to set the date from the datePicker as the text of the textfield
func textFieldDidBeginEditing(textField: UITextField)
 {
       textField.text = self.datePicker.date.dateString
}
and then the problem I mentioned happened

**Comment by raulriera** [comment]
Can you submit a demo project where this happens? Unable to reproduce it myself

**Comment by cartmanguo** [comment]
here's a simple project:
https://github.com/cartmanguo/demo

**Comment by raulriera** [comment]
You are right, it is not refreshing after the textfield has been drawn (I was setting the text in viewDidLoad and working for me)

The bug is at `animateViewsForTextEntry` where I am checking if its empty and then doing the animations. Simply removing the if won't work... will try to think of something. If you find a solution first, a PR would be appreciated

**Comment by raulriera** [comment]
Fixed in 46d668a

**Comment by LadyRanger1992** [comment]
hello, Raul.
This issue still visible in my app.
I using your library in Objective-C project, when I set text are emty string, the placeholder string do not move down.
//Objective-C
_nameText = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH*0.1667)];
    [_nameText setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
    [_nameText setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
    [_nameText setPlaceholder:@"  Name:"];
    [self.pageScroll addSubview:_nameText];
    yPos += WIDTH*0.1667 + 5;
    
    _title = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH*0.1667)];
    [_title setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
    [_title setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
    [_title setPlaceholder:@"  Title:"];
    [self.pageScroll addSubview:_title];
    yPos += WIDTH*0.1667 + 5;
    
    _comment = [[HoshiTextField alloc] initWithFrame:CGRectMake(xPos, yPos, WIDTH - 10, WIDTH*0.1667)];
    [_comment setBorderActiveColor:[UIColor LVL_colorWithHexString:@"ffc16a" andAlpha:1.0]];
    [_comment setBorderInactiveColor:[UIColor LVL_colorWithHexString:@"d0d0d0" andAlpha:1.0]];
    [_comment setPlaceholder:@"  Comment"];
    [self.pageScroll addSubview:_comment];
    yPos += WIDTH*0.1667 + 5;

//===========================================
//and when I call clear function like:
        [_nameText setText:@""];
        [_title setText:@""];
        [_comment setText:@""];
        [_nameText becomeFirstResponder];
the placeholder do not move down.
<I has update your code in Sept 30>

Thank & Regard,
-- Luc.
